"""empty message

Revision ID: 8afe558758c4
Revises: 07b7395b2b85
Create Date: 2021-08-19 16:01:55.619101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afe558758c4'
down_revision = '07b7395b2b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blog_title')
    # ### end Alembic commands ###
